- name: install NodeJs from NodeSource
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: install node
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: true 
  npm:
    name: pm2
    global: yes
    production: yes
    state: present