- name: install NodeJs from NodeSource
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: install node
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: install pm2
  npm:
    name: pm2
    global: yes