- name: create backend directory
  become: true
  file: 
    path: /home/ubuntu/udapeople-backend
    state: directory

- name: unarchive artifact
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/udapeople-backend

- name: install dependencies
  become: true 
  shell: |
    cd /home/ubuntu/udapeople-backend
    npm install

- name: execute app with PM2
  become: true 
  shell: |
    cd /home/ubuntu/udapeople-backend
    pm2 stop default
    pm2 start main.js
    